### ISSUE TITLE
No fileInfo  information.

### ISSUE THREAD

**Issue by BublilDaniel** [ppmetz/Serilog.Enrichers.WithCaller#9]
hi
i init my logger like this
`Logger = new LoggerConfiguration().ReadFrom.Configuration(config)
                 .Enrich.WithProcessId()
                 .Enrich.WithCaller(true)
                 .Enrich.WithProcessName()
                 .Enrich.WithThreadId().Enrich.WithThreadName().CreateLogger();`

and this is my output template:
`"outputTemplate": "{Timestamp:HH:mm:ss} <Process:{ProcessId}:{ProcessName}> <Thread:{ThreadId}:{ThreadName}> [{Level}] - {Message} (at {CallerFileName}:{CallerLineNo}){NewLine}{Exception}",`

and this two variables do not works, `{CallerFileName}:{CallerLineNo}` 
only `{Caller}` works but I don't want all that info.

I am using Nuget package version 1.2.0, no 1.30 is available like it says in the README

Thanks,
Daniel

**Comment by pmetz-steelcase** [comment]
Hello Daniel, thank you for feedback.

Sorry the version 1.3.0 did not pass some checks (reason is not clear to me), so it's not on nuget.org

I'll take your example and check what is the issue, maybe today there is a new beta version.

Cheers, 
Peter

**Comment by BublilDaniel** [comment]
Thanks!
let me know if you need a hand..

**Comment by pmetz-steelcase** [comment]
Hi Daniel, looks like we worked at same time on that :)

Please check out this: 
https://github.com/pmetz-steelcase/Serilog.Enrichers.WithCaller/tree/dev_basedOn120 
Yet, I did not create/push the nuget on nuget.org

Also I see your pull request - I need some time (to find the time) to check it

Thanks,
Peter

**Comment by ppmetz** [comment]
project is no more maintained,  
you may try [serilog-enrichers-callerinfo](https://github.com/pm4net/serilog-enrichers-callerinfo) 
https://www.nuget.org/packages?q=serilog-enrichers-callerinfo
